import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faHouse,
  faBook,
  faBookmark,
  faUserGraduate,
  faUser,
  faEyeSlash,
} from "@fortawesome/free-solid-svg-icons";

export const customStyles = {
  iconHome: faHouse,
  iconLessons: faBook,
  iconBookmark: faBookmark,
  inconUser: faUserGraduate,
  iconAuthuser: faUser,
  iconAuthpwd: faEyeSlash,
  headingFont: "Satoshi",
  headingSize: 32,
  headingColor: "#CC4646",
  headingIconEffect: "Drop Shadow",
  headingBorderColor: "#090909",
  headingBorderPosition: "inside",
  headingBorderSize: 0.5,
  h2Size: 24,
  buttonBackgroundColor: "#EEC1C0",
  buttonRadius: 12,
  buttonWidth: "90%",
  buttonHeight: 50,
  buttonTextSize: 20,
  buttonDisplay: "flex",
  buttonFlexDirection: "column",
  buttonAlignItems: "center",
  buttonJustifyContent: "center",
  defaultFontFamily: "Noto Sans JP",
  navBarBackgroundColor: "#EEC1C0",
  navBarBorderColor: "#070000",
  navBarIconSelectedColor: "#D56565",
  navBarIconSelectedBackgroundColor: "FFFFFF",
  navBarWidth: "90%",
  navBarHeight: 50,
  navBarRadius: 24,
  navBarCircleHeight: "7%",
  navBarCircleRadius: 100,
  navBarCircleBackgroundColor: "white",
};
